BASE_TASK_CONFIG_PATH: habitat_extensions/config/rxr_vlnce_english_task.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_IDS: [0]
TORCH_GPU_ID: 0
TRAINER_NAME: schedulesampler-CMA
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: logs/tensorboard_dirs/rxr_cma_en
CHECKPOINT_FOLDER: logs/checkpoints/rxr_cma_en
EVAL_CKPT_PATH_DIR: logs/checkpoints/rxr_cma_en
RESULTS_DIR: logs/eval_results/
VIDEO_OPTION: ["disk"]  # options: "disk", "tensorboard"
VIDEO_DIR: logs/videos/cma_rxr

INFERENCE:
  SPLIT: test_challenge
  LANGUAGES: [en-US, en-IN]
  SAMPLE: True
  USE_CKPT_CONFIG: False
  CKPT_PATH: data/checkpoints/ckpt.0.pth  # REPLACE THIS
  PREDICTIONS_FILE: rxr_cma_en_test_challenge.jsonl
  FORMAT: rxr

# data/checkpoints/rxr_cma_en/RxR-en-CMA.pth
EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  LANGUAGES: [en-US, en-IN]
  EPISODE_COUNT: 30
  # SAMPLE: True
  
RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ResizeShortestEdge, CenterCropperPerSensor]

# IL:
#   batch_size: 16
#   epochs: 15
#   inflection_weight_coef: 1.9
IL:
  epochs: 50
  batch_size: 16
  schedule_ratio: 0.75
  decay_time: 10
  max_traj_len: 20

  # RECOLLECT_TRAINER:
  #   preload_size: 30
  #   preload_trajectories_file: False
  #   trajectories_file: data/trajectories_dirs/rxr_en_guide_trim250/trajectories.json.gz
  #   max_traj_len: 250  # 1.3% of episodes in the English training split are above 250

# MODEL:
#   policy_name: CMAPolicy
#   INSTRUCTION_ENCODER:
#     bidirectional: True
#     sensor_uuid: rxr_instruction
#     embedding_size: 768
MODEL:
  policy_name: PolicyViewSelectionCMA
  spatial_output: False
  RGB_ENCODER:
    encode_size: 2048
    output_size: 512
  DEPTH_ENCODER:
    encode_size: 128
    output_size: 256
    ddppo_checkpoint: data/pretrained_models/ddppo-models/gibson-2plus-resnet50.pth
  VISUAL_DIM:
    vis_hidden: 512
    directional: 64
  INSTRUCTION_ENCODER:
    bidirectional: True
    use_pretrained_embeddings: False
    embedding_size: 256
    hidden_size: 256

  #  INSTRUCTION_ENCODER:
  #   bidirectional: True
  #   use_pretrained_embeddings: False
  #   embedding_size: 256
  #   hidden_size: 256

